version: '3.4'

services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "Pwd12345!"
    volumes:
      - ./data/mssql:/var/opt/mssql/data
    ports:
      - '1433:1433'
    expose:
      - '1433'
  web:
    image: ${DOCKER_REGISTRY-}web
    build:
      context: .
      dockerfile: Web/Dockerfile
    ports:
     - '5001:443'